#!/usr/bin/env bash
# Build Ghidra's decompiler + the pyre bridge into a wasm module the
# web frontend loads in a Web Worker.
#
# Outputs (under dist/):
#   pyre_decompiler.js     ES module loader
#   pyre_decompiler.wasm   compiled code
#
# Spec files are NOT bundled here — the worker fetches them at runtime
# into emscripten's virtual FS via FS.createLazyFile, lazy-mounting one
# processor at a time.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$SCRIPT_DIR/src"
GHIDRA_DIR="$SCRIPT_DIR/third_party/ghidra-decompiler"
BUILD_DIR="$SCRIPT_DIR/build"
OUT_DIR="$SCRIPT_DIR/dist"

# Source emsdk if emcc isn't already on PATH. Honors common install
# locations; if you have emsdk somewhere else, source emsdk_env.sh
# yourself before invoking this script.
if ! command -v emcc >/dev/null 2>&1; then
    for env in \
        "$HOME/wasm/emsdk/emsdk_env.sh" \
        "$HOME/emsdk/emsdk_env.sh" \
        "/opt/emsdk/emsdk_env.sh" \
        "/emsdk/emsdk_env.sh"; do
        if [[ -f "$env" ]]; then
            # shellcheck source=/dev/null
            . "$env" >/dev/null 2>&1 || true
            break
        fi
    done
fi
if ! command -v emcc >/dev/null 2>&1; then
    echo "error: emcc not found — source emsdk_env.sh first" >&2
    exit 1
fi

mkdir -p "$BUILD_DIR" "$OUT_DIR"

# Source list mirrors the user's working CMakeLists.txt exactly
# (resources/decompiler/third_party/ghidra-decompiler/CMakeLists.txt).
# Listed positively rather than negatively so a new file in the
# vendored tree doesn't accidentally get pulled in.
BASE_SOURCES=(
    marshal.cc space.cc float.cc address.cc pcoderaw.cc translate.cc
    opcodes.cc globalcontext.cc
)

DECOMPILER_SOURCES=(
    capability.cc architecture.cc options.cc graph.cc cover.cc block.cc
    cast.cc typeop.cc database.cc cpool.cc comment.cc stringmanage.cc
    modelrules.cc fspec.cc action.cc loadimage.cc varnode.cc op.cc type.cc
    variable.cc varmap.cc jumptable.cc emulate.cc emulateutil.cc flow.cc
    userop.cc expression.cc multiprecision.cc funcdata.cc funcdata_block.cc
    funcdata_varnode.cc unionresolve.cc funcdata_op.cc pcodeinject.cc
    heritage.cc prefersplit.cc rangeutil.cc ruleaction.cc subflow.cc
    transform.cc blockaction.cc merge.cc double.cc coreaction.cc condexe.cc
    override.cc dynamic.cc crc32.cc prettyprint.cc printlanguage.cc
    printc.cc printjava.cc memstate.cc opbehavior.cc paramid.cc
    string_ghidra.cc constseq.cc
)

SLGH_SOURCES=(
    sleigh.cc sleigh_arch.cc inject_sleigh.cc pcodecompile.cc sleighbase.cc
    slghsymbol.cc slghpatexpress.cc slghpattern.cc semantics.cc context.cc
    slaformat.cc compression.cc filemanage.cc
)

LIBDECOMP_SOURCES=(libdecomp.cc)

# Bison/flex-generated parsers define conflicting `static yypgoto` etc.
# in each TU — they MUST compile in their own translation units. Unity
# inclusion of these would fail to link.
STANDALONE_SOURCES=(grammar.cc xml.cc pcodeparse.cc)

# Compose the unity .cc by #include'ing every file from the lists
# above except the standalone parsers. Driving this off arrays (vs.
# walking the directory) means a new vendored file isn't surprise-
# included until we explicitly list it.
UNITY_FILE="$BUILD_DIR/ghidra_unity.cc"
{
    echo "// Auto-generated by build.sh. Do not edit."
    for f in "${BASE_SOURCES[@]}" "${DECOMPILER_SOURCES[@]}" \
             "${SLGH_SOURCES[@]}" "${LIBDECOMP_SOURCES[@]}"; do
        echo "#include \"$GHIDRA_DIR/$f\""
    done
} > "$UNITY_FILE"

# -Os: optimize for code size — shaves ~30% off wasm bytes vs. -O3.
# -fexceptions: legacy setjmp-based exception model. Native wasm
#   exceptions would be faster but Safari support was still spotty as
#   of 2025; revisit when usage stats permit.
# -sUSE_ZLIB=1: pulls in emscripten's zlib port (Ghidra uses it for
#   compressed .sla decoding).
# -w: silence Ghidra's warning storm.
CXXFLAGS=(
    -Os -std=c++17 -fexceptions -w
    -sUSE_ZLIB=1
    -I"$GHIDRA_DIR" -I"$SRC_DIR"
)

echo "[build] compiling unity + standalone parsers + bridge in parallel..."

# Run per-TU compiles in parallel; collect pids so we can fail loudly
# if any of them die. wait -n loop isn't portable to macOS bash 3.x.
pids=()
em++ "${CXXFLAGS[@]}" -c "$UNITY_FILE" -o "$BUILD_DIR/ghidra_unity.o" & pids+=($!)
for f in "${STANDALONE_SOURCES[@]}"; do
    em++ "${CXXFLAGS[@]}" -c "$GHIDRA_DIR/$f" -o "$BUILD_DIR/${f%.cc}.o" & pids+=($!)
done
em++ "${CXXFLAGS[@]}" -c "$SRC_DIR/WebLoadImage.cpp" -o "$BUILD_DIR/WebLoadImage.o" & pids+=($!)
em++ "${CXXFLAGS[@]}" -c "$SRC_DIR/WebArchitecture.cpp" -o "$BUILD_DIR/WebArchitecture.o" & pids+=($!)
em++ "${CXXFLAGS[@]}" -c "$SRC_DIR/bridge.cpp" -o "$BUILD_DIR/bridge.o" & pids+=($!)

fail=0
for pid in "${pids[@]}"; do
    if ! wait "$pid"; then fail=1; fi
done
if [[ $fail -ne 0 ]]; then
    echo "[build] compile failed" >&2
    exit 1
fi

# Every KEEPALIVE'd symbol from bridge.cpp must appear here, plus
# malloc/free since the bridge hands malloc'd buffers back to JS and
# JS pre-allocates HEAPU8 slabs for region copies.
EXPORTED_FUNCS='[
  "_pyre_init",
  "_pyre_add_spec_dir",
  "_pyre_create",
  "_pyre_add_region",
  "_pyre_add_symbol",
  "_pyre_add_string",
  "_pyre_add_readonly",
  "_pyre_decompile",
  "_pyre_free_string",
  "_pyre_destroy",
  "_malloc",
  "_free"
]'

# FS / lazy-file machinery is what makes the worker's per-arch lazy
# mount work — UTF8ToString/HEAPU8 are how we marshal strings and
# region bytes across the JS/wasm boundary.
RUNTIME_METHODS='[
  "ccall",
  "cwrap",
  "FS",
  "UTF8ToString",
  "stringToUTF8",
  "lengthBytesUTF8",
  "HEAPU8",
  "HEAP8"
]'

echo "[build] linking..."

# -sALLOW_MEMORY_GROWTH=1: a single decompile of a large function can
#   spike heap usage; growth is cheaper than over-allocating up front.
# -sINITIAL_MEMORY=67108864 (64MB): big enough to load typical specs
#   + decompile small functions without an immediate grow.
# -sWASM_BIGINT=1: lets us pass uint64_t addresses from JS BigInt
#   without a 32-bit truncation hop.
# -sMODULARIZE=1 + EXPORT_ES6=1: clean ES module interface — the
#   worker does `import PyreDecompiler from './...'`.
# -sENVIRONMENT=worker,web: trims the runtime; we never run in node.
# -sFORCE_FILESYSTEM=1: needed because LazyFile registration in the
#   worker may happen before the first FS access (so emscripten's
#   "no FS used, drop it" optimizer must be disabled).
em++ \
    -Os \
    -fexceptions \
    -sUSE_ZLIB=1 \
    -sALLOW_MEMORY_GROWTH=1 \
    -sINITIAL_MEMORY=67108864 \
    -sWASM_BIGINT=1 \
    -sMODULARIZE=1 \
    -sEXPORT_ES6=1 \
    -sEXPORT_NAME=PyreDecompiler \
    -sENVIRONMENT=worker,web \
    -sEXPORTED_FUNCTIONS="$EXPORTED_FUNCS" \
    -sEXPORTED_RUNTIME_METHODS="$RUNTIME_METHODS" \
    -sFORCE_FILESYSTEM=1 \
    -o "$OUT_DIR/pyre_decompiler.js" \
    "$BUILD_DIR/ghidra_unity.o" \
    "$BUILD_DIR/grammar.o" \
    "$BUILD_DIR/xml.o" \
    "$BUILD_DIR/pcodeparse.o" \
    "$BUILD_DIR/WebLoadImage.o" \
    "$BUILD_DIR/WebArchitecture.o" \
    "$BUILD_DIR/bridge.o"

echo "[build] done: $OUT_DIR/pyre_decompiler.{js,wasm}"
ls -la "$OUT_DIR"
